add support to launch adminer
kurtosis-tech/postgres-package pull request #10
Opened 2023-10-16 17:50 UTC by bharath-123

2023-10-17 08:01 UTC, h4ck3rk3y commented on main.star
> +    launch_adminer=False,
lets add this at the end!

2023-10-17 19:18 UTC, bharath-123 commented on kurtosis.yml
> +name: "github.com/bharath-123/postgres-package"
yes!

2023-10-17 19:18 UTC, bharath-123 commented on main.star
> +    launch_adminer=False,
done!

2023-10-17 19:27 UTC, bharath-123 commented on main.star
> +        adminer = adminer_module.run(plan)
<img width="635" alt="Screenshot 2023-10-18 at 12 55 21 AM" src="https://github.com/kurtosis-tech/postgres-package/assets/21315653/302a2f27-3f47-4984-a7aa-2e1b719c0168">

The user can specify the database's server, username and password in the UI. They can also select whether they want to connect to postgres, mysql etc

2023-10-18 09:27 UTC, h4ck3rk3y commented on main.star
> +<<<<<<< HEAD
hey you have a merge conflict left here

2023-10-18 09:29 UTC, h4ck3rk3y commented on main.star
> +        adminer = adminer_module.run(plan)
oh alright, is it possible though to have an instance that's configured from the beginning - reduces steps for the user. feels more integrated; say via ENV_VARS

say like - https://stackoverflow.com/questions/64110948/docker-compose-mariadb-with-adminer

2023-10-18 09:32 UTC, bharath-123 commented on main.star
> +        adminer = adminer_module.run(plan)
got it! will investigate it!

2023-10-18 09:32 UTC, bharath-123 commented on main.star
> +<<<<<<< HEAD
yikes! I will fix this. not sure how this got pushed! apologies!

2023-10-23 10:38 UTC, h4ck3rk3y commented on kurtosis.yml
> +name: "github.com/bharath-123/postgres-package"
```suggestion
name: "github.com/postgres-package/postgres-package"
```

I am guessing this is because of the whole forking issue

2023-10-23 10:39 UTC, h4ck3rk3y approved these changes

2023-10-23 10:39 UTC, h4ck3rk3y commented on main.star
> +    )
lets slot in a new line

2023-10-23 10:39 UTC, h4ck3rk3y commented on main.star
> +            default_driver="pgsql",
can we take out PGSQL as a constant!

2023-10-23 17:05 UTC, h4ck3rk3y commented on main.star
> +    launch_adminer=True,
lets make this False by default

2023-10-26 07:44 UTC, bharath-123 commented on main.star
> +            default_driver="pgsql",
done!

2023-10-26 07:44 UTC, bharath-123 commented on main.star
> +    launch_adminer=True,
done!

2023-10-26 16:39 UTC, h4ck3rk3y approved these changes

2023-10-26 16:39 UTC, h4ck3rk3y commented on main.star
> +    persistent=False,
Persistent needs to be True by default!!

2023-10-26 16:39 UTC, h4ck3rk3y commented on main.star
> +        persistent (bool): Whether the data should be persisted. Defaults to False; Note that this isn't supported on multi node k8s cluster as of 2023-10-16
persistent needs to be true; don't change this doc string

2023-10-26 16:40 UTC, h4ck3rk3y requested changes

2023-10-26 16:40 UTC, h4ck3rk3y commented on main.star
> +        persistent (bool): Whether the data should be persisted. Defaults to False; Note that this isn't supported on multi node k8s cluster as of 2023-10-16
adding another comment so that i can `request changes` isntead

2023-10-27 10:35 UTC, h4ck3rk3y approved these changes

2023-10-30 17:41 UTC, merged